
version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: e-commerce-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ratelimiterdb
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis-cache:
    image: redis:7-alpine
    container_name: e-commerce-redis-cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: